FROM ubuntu:14.04
MAINTAINER Jean Baptiste Favre <docker@jbfavre.org>

ENV SHELL "/bin/bash"
ENV DEBIAN_FRONTEND noninteractive
ENV TERM 1

ADD scripts/debian_cleaner.sh /tmp/

RUN /usr/bin/apt-get update -yqq \
 && /usr/bin/apt-get upgrade --no-install-recommends -yqq \
 && /usr/bin/apt-get install --no-install-recommends -yqq curl ca-certificates \
 && echo '192.168.42.53 apt.jbfav.re' >> /etc/hosts \
 && echo 'deb http://apt.jbfav.re/release/vertica72/ wheezy main'> /etc/apt/sources.list.d/vertica.list \
 && /usr/bin/curl -SL http://apt.jbfav.re/release/key.gpg | /usr/bin/apt-key add - \
 && /usr/bin/apt-get update -yqq \
 && /usr/bin/chsh -s /bin/bash root \
 && /bin/rm /bin/sh && ln -s /bin/bash /bin/sh \
 && /usr/bin/curl -o /usr/local/bin/gosu -SL 'https://github.com/tianon/gosu/releases/download/1.1/gosu' \
 && /bin/chmod +x /usr/local/bin/gosu \
 && /usr/sbin/groupadd -r verticadba \
 && /usr/sbin/useradd -r -m -s /bin/bash -g verticadba dbadmin \
 && /usr/local/bin/gosu dbadmin mkdir /tmp/.python-eggs \
 && /usr/sbin/locale-gen en_US en_US.UTF-8 \
 && /usr/sbin/dpkg-reconfigure locales \
 && /usr/bin/apt-get install --no-install-recommends -yqq openssh-server openssh-client mcelog sysstat dialog libexpat1 \
 && /usr/bin/apt-get install --no-install-recommends -yqq vertica \
 && /opt/vertica/sbin/install_vertica --license CE --accept-eula --hosts 127.0.0.1 \
                                      --dba-user-password-disabled --failure-threshold NONE --no-system-configuration \
 && gosu dbadmin /opt/vertica/bin/admintools -t create_db -s localhost -d docker -c /home/dbadmin/docker/catalog -D /home/dbadmin/docker/data \
 && /usr/bin/apt-get remove --purge -y curl ca-certificates libpython2.7 \
 && /bin/rm /etc/apt/sources.list.d/vertica.list \
 && /usr/bin/apt-key del DB0AA004 \
 && /bin/bash /tmp/debian_cleaner.sh

ENV PYTHON_EGG_CACHE /tmp/.python-eggs
ENV VERTICADATA /home/dbadmin/docker
VOLUME /home/dbadmin/docker
ENTRYPOINT ["/opt/vertica/bin/docker-entrypoint.sh"]
ADD ./docker-entrypoint.sh /opt/vertica/bin/
ADD ./install-vertica-ml.sh /opt/vertica/bin/

EXPOSE 5433
