FROM ubuntu:12.04
MAINTAINER Jean Baptiste Favre <docker@jbfavre.org>

ARG VERTICA_PACKAGE="unknown"

ENV SHELL "/bin/bash"
ENV DEBIAN_FRONTEND noninteractive
ENV TERM 1

ADD packages/${VERTICA_PACKAGE} /tmp/
ADD scripts/debian_cleaner.sh /tmp/

RUN /usr/bin/apt-get update -yqq \
 && /usr/bin/apt-get upgrade --no-install-recommends -yqq \
 && /usr/bin/apt-get install --no-install-recommends -yqq curl ca-certificates \
 && /usr/bin/chsh -s /bin/bash root \
 && /bin/rm /bin/sh && ln -s /bin/bash /bin/sh \
 && /usr/bin/curl -o /usr/local/bin/gosu -SL 'https://github.com/tianon/gosu/releases/download/1.1/gosu' \
 && /bin/chmod +x /usr/local/bin/gosu \
 && /usr/sbin/groupadd -r verticadba \
 && /usr/sbin/useradd -r -m -s /bin/bash -g verticadba dbadmin \
 && /usr/local/bin/gosu dbadmin mkdir /tmp/.python-eggs \
 && /usr/sbin/locale-gen en_US en_US.UTF-8 \
 && /usr/sbin/dpkg-reconfigure locales \
 && echo "dbadmin -       nice    0" >> /etc/security/limits.conf \
 && echo "dbadmin -       nofile  65536" >> /etc/security/limits.conf \
 && apt-get install -yqq openssh-server openssh-client mcelog sysstat dialog libexpat1 sudo libdbi-perl net-tools \
 && export PYTHON_EGG_CACHE=/tmp/.python-eggs \
 && /usr/bin/dpkg -i /tmp/${VERTICA_PACKAGE} \
 && /opt/vertica/sbin/install_vertica --license CE --accept-eula --hosts 127.0.0.1 --dba-user-password-disabled --failure-threshold NONE --no-system-configuration \
 && gosu dbadmin /opt/vertica/bin/admintools -t create_db -s 127.0.0.1 -d docker -c /home/dbadmin/docker/catalog -D /home/dbadmin/docker/data \
 && /usr/bin/apt-get remove --purge -y curl ca-certificates \
 && /bin/bash /tmp/debian_cleaner.sh

ENV VERTICADATA /home/dbadmin/docker
VOLUME /home/dbadmin/docker
ADD ./docker-entrypoint.sh /opt/vertica/bin/
ENTRYPOINT ["/opt/vertica/bin/docker-entrypoint.sh"]

EXPOSE 5433
